services:
  db:
    image: postgres:16.4-bullseye
    # restart: always
    restart: unless-stopped
    volumes:
      - /home/juandd5/docker-volumes/postgres16.4:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: juandd5
      POSTGRES_PASSWORD: my-user-pass
      PGDATA: /var/lib/postgresql/data/pgdata